---
services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    _instanceof:
        Symfony\Component\Messenger\Handler\MessageHandlerInterface:
            tags:
                - { name: 'messenger.message_handler', bus: 'messenger.default_bus' }

    Asylamba\Modules\Atlas\Handler\:
        resource: '%root_path%/system/Modules/Atlas/Handler/*'

    Asylamba\Modules\Atlas\Handler\PlayerRankingHandler:
        arguments:
            $dataAnalysis: '%data_analysis%'

    Asylamba\Modules\Atlas\Handler\FactionRankingHandler:
        arguments:
            $serverStartTime: '%server_start_time%'
            $hoursBeforeStartOfRanking: '%hours_before_start_of_ranking%'
            $pointsToWin: '%points_to_win%'

    Asylamba\Modules\Atlas\Manager\:
        resource: '%root_path%/system/Modules/Atlas/Manager/*'

    Asylamba\Modules\Atlas\Manager\RankingManager:
        arguments:
            $pointsToWin: '%points_to_win%'
            $jeanMiId: '%id_jeanmi%'
