---
services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    _instanceof:
        Symfony\Component\Messenger\Handler\MessageHandlerInterface:
            tags:
                - { name: 'messenger.message_handler', bus: 'messenger.default_bus' }

    Asylamba\Modules\Atlas\Manager\:
        resource: '%root_path%/system/Modules/Atlas/Manager/*'

    Asylamba\Modules\Atlas\Manager\RankingManager:
        arguments:
            $pointsToWin: '%points_to_win%'
            $jeanMiId: '%id_jeanmi%'
