---
services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    Asylamba\Modules\Atlas\Manager\:
        resource: '%root_path%/system/Modules/Atlas/Manager/*'

    Asylamba\Modules\Atlas\Manager\RankingManager:
        arguments:
            $pointsToWin: '%points_to_win%'
            $jeanMiId: '%id_jeanmi%'
