faction_bonuses:
    - id: 0
      title: '5% de défense'
      desc: 'Vos vaisseaux gagnent en défense'
    - id: 1
      title: '5% prix'
      desc: 'Les croiseurs et croiseurs-lourds sont moins chers'
    - id: 2
      title: '10% de maniabilité'
      desc: 'Vos vaisseaux du Chantier Alpha gagnent en maniabilité'
    - id: 3
      title: '5% de défense'
      desc: 'Vos vaisseaux du Chantier de Ligne perdent en défense'
    - id: 4
      title: '5% production'
      desc: 'Vos routes commerciales produisent plus de crédits'
    - id: 5
      title: '3% prix'
      desc: 'Vos routes commerciales coûtent moins de crédits'
    - id: 6
      title: '3% de crédits'
      desc: 'Vos impôts vous amènent plus de crédits'
    - id: 7
      title: '10% prix'
      desc: 'Vos colonisations et conquêtes sont moins chères'
    - id: 8
      title: '5% de ressources'
      desc: 'Une partie des ressources pillées sont offertes aux Dieux'
    - id: 9
      title: '4% production'
      desc: 'Votre Raffinerie produit plus de ressources'
    - id: 10
      title: '4% stockage'
      desc: 'Votre Raffinerie stocke plus de ressources'
    - id: 11
      title: '4% efficacité'
      desc: 'Votre Université est plus efficace'
    - id: 12
      title: '2% temps'
      desc: 'Vos technologies se développent plus rapidement'
    - id: 13
      title: '6% efficacité'
      desc: 'Votre Ecole de Commandement est plus efficace'
    - id: 14
      title: '2% efficacité'
      desc: 'Votre Université est plus efficace'
