twig_component:
    anonymous_template_directory: 'components/'
    defaults:
        # Namespace & directory for components
        App\Modules\Ares\Infrastructure\Twig\Components\: 'components/fleet/'
