twig_component:
    anonymous_template_directory: 'components/'
    defaults:
        # Namespace & directory for components
        App\Modules\Shared\Infrastructure\Twig\Components\: 'components/'
        App\Modules\Demeter\Infrastructure\Twig\Components\: 'components/Faction/'
