twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        app_subname: '%app_subname%'
        app_description: '%app_description%'
        color_style: '%color_style%'

when@test:
    twig:
        strict_variables: true
