services:
    phpfpm:
        volumes:
            - ./docker/fpm/config/php-dev.ini:/usr/local/etc/php/conf.d/php-dev.ini:ro

    ###> symfony/mercure-bundle ###
    mercure:
        environment:
            # Uncomment the following line to disable HTTPS,
            SERVER_NAME: ':80'
            #SERVER_NAME: 'mercure.kalaxia.local'
            MERCURE_PUBLISHER_JWT_KEY: '2eeDS20V0ySXnFwZFZMTp2B0aoCLqVdDzadiazjdaizd'
            MERCURE_SUBSCRIBER_JWT_KEY: '2eeDS20V0ySXnFwZFZMTp2B0aoCLqVdDzadiazjdaizd'
            MERCURE_EXTRA_DIRECTIVES: |
                cors_origins https://kalaxia.local
        # command: /usr/bin/caddy run --config /etc/caddy/dev.Caddyfile
    ###< symfony/mercure-bundle ###

    rabbitmq:
        environment:
            RABBITMQ_DEFAULT_USER: kalaxia
            RABBITMQ_DEFAULT_PASSWORD: kalaxia

    mariadb:
        environment:
            MARIADB_ROOT_PASSWORD: kalaxia
            MARIADB_USER: kalaxia
            MARIADB_PASSWORD: kalaxia

    supervisord:
        volumes:
            - ./docker/supervisord/config/php-prod.ini:/usr/local/etc/php/conf.d/php-prod.ini:ro
