networks:
    asylamba:
        driver: bridge
    mongo:
        driver: bridge

volumes:
    db-data:
    rabbitmq-data:
    redis-data:

services:
    mariadb:
        container_name: asylamba_mariadb
        image: mariadb:10
        environment:
            MARIADB_DATABASE: ${MARIADB_DATABASE:-asylamba_game}
            MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD:-asylamba}
            MARIADB_USER: ${MARIADB_USER:-asylamba}
            MARIADB_PASSWORD: ${MARIADB_PASSWORD:-asylamba}
        networks:
            - asylamba
        ports:
            - "3306:3306"
        volumes:
            # mysql
            - db-data:/var/lib/mysql

    redis:
        container_name: asylamba_redis
        image: redis
        networks:
            - asylamba
        ports:
            - "6379:6379"

    rabbitmq:
        container_name: asylamba_rabbitmq
        image: rabbitmq:3.9-management-alpine
        ports:
            - "5672:5672"
            - "15672:15672"
        volumes:
            - rabbitmq-data:/var/lib/rabbitmq
        networks:
            - asylamba
