version: '3'

volumes:
    caddy_data:
    caddy_config:

services:
    phpfpm:
        container_name: kalaxia_app
        build: docker/fpm
        env_file: '.env.prod'
        volumes:
            - "./:/srv/app"
        networks:
            - asylamba

    caddy:
        container_name: kalaxia_caddy_webserver
        image: caddy
        depends_on:
            - 'phpfpm'
        ports:
            - '80:80'
            - '443:443'
        volumes:
            - './docker/caddy/Caddyfile:/etc/caddy/Caddyfile'
            - './:/srv/app'
            - caddy_data:/data
            - caddy_config:/config
        networks:
            - asylamba

    supervisord:
        container_name: kalaxia_worker
        build: docker/supervisord
        env_file: '.env.prod'
        volumes:
            - "./:/srv/app"
            - "./var/logs/supervisord/:/var/log/supervisord/"
            - "./supervisord.conf:/etc/supervisor/supervisord.conf"
        networks:
            - asylamba


