delete_all_spy_reports:
    path: /spy-reports/delete-all
    controller: App\Modules\Athena\Infrastructure\Controller\Base\Building\RefineryController

delete_spy_report:
    path: /spy-reports/{id}/delete
    controller: App\Modules\Athena\Infrastructure\Controller\Base\Building\RefineryController

spy:
    path: /spy
    controller: App\Modules\Athena\Infrastructure\Controller\Base\Building\RefineryController
