embassy:
    path: /embassy
    controller: App\Modules\Demeter\Infrastructure\Controller\ViewEmbassy

faction_overview:
    path: /faction
    controller: App\Modules\Demeter\Infrastructure\Controller\ViewOverview

faction_members:
    path: /faction/members
    controller: App\Modules\Demeter\Infrastructure\Controller\ViewMembers

faction_government:
    path: /faction/government
    controller: App\Modules\Demeter\Infrastructure\Controller\ViewGovernment

faction_data:
    path: /faction/data
    controller: App\Modules\Demeter\Infrastructure\Controller\ViewData

faction_forum:
    path: /faction/forum/{forumId}
    controller: App\Modules\Demeter\Infrastructure\Controller\ViewForum
    defaults:
        forumId: null

view_forum_topic:
    path: /faction/forum/{forumId}/topics/{topicId}
    controller: App\Modules\Demeter\Infrastructure\Controller\Forum\ViewTopic

write_forum_message:
    path: /faction/forum/{forumId}/topics/{topicId}/messages
    controller: App\Modules\Demeter\Infrastructure\Controller\Forum\WriteMessage
    methods: ['POST']

edit_forum_message:
    path: /faction/forum/{forumId}/topics/{topicId}/messages/{messageId}
    controller: App\Modules\Demeter\Infrastructure\Controller\Forum\EditMessage
    methods: ['POST']

create_forum_topic:
    path: /faction/forum/{forumId}/topics
    controller: App\Modules\Demeter\Infrastructure\Controller\Forum\CreateTopic
    methods: ['POST']

faction_senate:
    path: /faction/senate
    controller: App\Modules\Demeter\Infrastructure\Controller\ViewSenate

view_faction_election:
    path: /faction/election
    controller: App\Modules\Demeter\Infrastructure\Controller\ViewElection

initiate_faction_coup:
    path: /faction/coup
    controller: App\Modules\Demeter\Infrastructure\Controller\MakeACoup

abdicate:
    path: /abdicate
    controller: App\Modules\Demeter\Infrastructure\Controller\Government\Ruler\Abdicate

resign:
    path: /resign
    controller: App\Modules\Demeter\Infrastructure\Controller\Government\Resign

write_faction_conversation:
    path: /faction/write-conversation
    controller: App\Modules\Demeter\Infrastructure\Controller\Government\WriteToFaction

create_law:
    path: /faction/law/create
    controller: App\Modules\Demeter\Infrastructure\Controller\Government\CreateLaw

send_credits_from_faction:
    path: /faction/send-credits
    controller: App\Modules\Demeter\Infrastructure\Controller\Government\SendCredits

update_faction_description:
    path: /faction/update-description
    controller: App\Modules\Demeter\Infrastructure\Controller\Government\UpdateDescription

pin_faction_news:
    path: /faction/news/{id}/pin
    controller: App\Modules\Demeter\Infrastructure\Controller\News\Pin

create_faction_news:
    path: /faction/news/create
    controller: App\Modules\Demeter\Infrastructure\Controller\News\Create

edit_faction_news:
    path: /faction/news/{id}/edit
    controller: App\Modules\Demeter\Infrastructure\Controller\News\Edit

delete_faction_news:
    path: /faction/news/{id}/delete
    controller: App\Modules\Demeter\Infrastructure\Controller\News\Delete

choose_minister:
    path: /faction/government/{department}/choose-minister
    controller: App\Modules\Demeter\Infrastructure\Controller\Government\Ruler\ChooseMinister

fire_minister:
    path: /faction/government/ministers/{id}/fire
    controller: App\Modules\Demeter\Infrastructure\Controller\Government\Ruler\FireMinister

postulate:
    path: /faction/elections/{id}/postulate
    controller: App\Modules\Demeter\Infrastructure\Controller\Postulate

vote_for_candidate:
    path: /faction/elections/{electionId}/candidates/{candidateId}/vote
    controller: App\Modules\Demeter\Infrastructure\Controller\VoteForCandidate

vote_for_law:
    path: /faction/laws/{id}/vote
    controller: App\Modules\Demeter\Infrastructure\Controller\VoteForLaw
