embassy:
    path: /embassy
    controller: App\Modules\Demeter\Infrastructure\Controller\ViewEmbassy

faction:
    path: /faction
    controller: App\Modules\Demeter\Infrastructure\Controller\FactionController
