university:
    path: /university
    controller: App\Modules\Promethee\Infrastructure\Controller\ViewUniversity

update_university_category_investments:
    path: /api/university/{category<natural|life|social|informatic>}/{operation<increase|decrease>}
    methods: 'PATCH'
    controller: App\Modules\Promethee\Infrastructure\Controller\UpdateUniversityInvestments
