homepage:
    path: /
    controller: App\Shared\Infrastructure\Controller\HomepageController

registration:
    path: /create-character/{bindKey}/{highMode}
    controller: App\Shared\Infrastructure\Controller\RegistrationController
    defaults:
        highMode: false

connect:
    path: /connect/{bindKey}
    controller: App\Shared\Infrastructure\Controller\ConnectController

logout:
    path: /logout
    controller: App\Shared\Infrastructure\Controller\LogoutController

params:
    path: /params
    controller: App\Shared\Infrastructure\Controller\ParamsController
