homepage:
    path: /
    controller: App\Shared\Infrastructure\Controller\HomepageController

connect:
    path: /connect/{bindKey}
    controller: App\Shared\Infrastructure\Controller\ConnectController

logout:
    path: /logout
    controller: App\Shared\Infrastructure\Controller\LogoutController

params:
    path: /params
    controller: App\Shared\Infrastructure\Controller\ParamsController

switch_param:
    path: /param
    controller: App\Shared\Infrastructure\Controller\SwitchParam
