homepage:
    path: /
    controller: App\Shared\Controller\HomepageController

registration:
    path: /create-character/{bindKey}/{highMode}
    controller: App\Shared\Controller\RegistrationController
    defaults:
        highMode: false

connect:
    path: /connect/{bindKey}
    controller: App\Shared\Controller\ConnectController
