create_character:
    path: /create-character/{step}/{highMode}
    controller: App\Modules\Zeus\Infrastructure\Controller\CreateCharacter
    methods: ['GET', 'POST']
    defaults:
        highMode: false
        step: 'faction-choice'
    requirements:
        step: faction-choice|profile|place-choice|save

profile:
    path: /profile
    controller: App\Modules\Zeus\Infrastructure\Controller\ProfileController

tutorial_validatestep:
    path: /tutorial/validate-step
    controller: App\Modules\Zeus\Infrastructure\Controller\Tutorial\StepValidationController

sponsorship:
    path: /sponsorship
    controller: App\Modules\Zeus\Infrastracture\Controller\SponsorController

autocomplete_player:
    path: /api/players/search
    controller: App\Modules\Zeus\Infrastructure\Controller\AutocompletePlayers

switch_param:
    path: /switch_param
    controller: App\Modules\Zeus\Infrastructure\Controller\AutocompletePlayers

