---
services:
    hephaistos.technical_manager:
        class: Asylamba\Modules\Hephaistos\Manager\TechnicalManager
        arguments:
            - "@entity_manager"
            - "@api"
            - "%apimode"
            - "@zeus.player_manager"
            - "%zeus.player.inactive_time_limit"
            - "%zeus.player.global_inactive_time"
            - "%hermes.notifications.timeout.read"
            - "%hermes.notifications.timeout.unread"
            
    hephaistos.charge_manager:
        class: Asylamba\Modules\Hephaistos\Manager\ChargeManager
        arguments:
            - "@entity_manager"
            
    hephaistos.donation_manager:
        class: Asylamba\Modules\Hephaistos\Manager\DonationManager
        arguments:
            - "@entity_manager"
            - "@zeus.player_manager"
            - "@session_wrapper"
            - "%stripe_api_key"
            
    hephaistos.transaction_manager:
        class: Asylamba\Modules\Hephaistos\Manager\TransactionManager
        arguments:
            - "@entity_manager"