---
parameters:
    promethee.research.coeff: 1
    promethee.research.max_diff: 3
    promethee.research.quantity: 10

    promethee.technology_queue.resource_refund: 0.5
    promethee.technology_queue.credit_refund: 0.5    
    
services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    _instanceof:
        Symfony\Component\Messenger\Handler\MessageHandlerInterface:
            tags:
                - { name: 'messenger.message_handler', bus: 'messenger.default_bus' }

    App\Modules\Promethee\Handler\:
        resource: '%kernel.project_dir%/src/Modules/Promethee/Handler/*'

    App\Modules\Promethee\Manager\:
        resource: '%kernel.project_dir%/src/Modules/Promethee/Manager/*'

    App\Modules\Promethee\Helper\ResearchHelper:
        arguments:
            $researchCoeff: "%promethee.research.coeff%"
            $researchMaxDiff: "%promethee.research.max_diff%"

    App\Modules\Promethee\Helper\TechnologyHelper:
        arguments:
            $researchQuantity: "%promethee.research.quantity%"
    
    App\Modules\Promethee\Manager\ResearchManager:
        arguments:
            $researchQuantity: "%promethee.research.quantity%"
