factions:
    - id: !php/const App\Modules\Demeter\Resource\ColorResource::NO_FACTION
      regime: !php/const App\Modules\Demeter\Model\Color::REGIME_DEMOCRATIC
      bonus: []
      mandateDuration: 0

    - id: !php/const App\Modules\Demeter\Resource\ColorResource::KALANKAR
      regime: !php/const App\Modules\Demeter\Model\Color::REGIME_DEMOCRATIC
      bonus:
          - !php/const App\Modules\Demeter\Resource\ColorResource::DEFENSELITTLESHIPBONUS
          - !php/const App\Modules\Demeter\Resource\ColorResource::PRICEBIGSHIPBONUS
      mandateDuration: 604800

    - id: !php/const App\Modules\Demeter\Resource\ColorResource::VALKAR
      regime: !php/const App\Modules\Demeter\Model\Color::REGIME_ROYALISTIC
      bonus:
          - !php/const App\Modules\Demeter\Resource\ColorResource::SPEEDLITTLESHIPBONUS
          - !php/const App\Modules\Demeter\Resource\ColorResource::DEFENSELITTLESHIPMALUS
      mandateDuration: 604800

    - id: !php/const App\Modules\Demeter\Resource\ColorResource::FALKIRR
      regime: !php/const App\Modules\Demeter\Model\Color::REGIME_ROYALISTIC
      bonus:
        - !php/const App\Modules\Demeter\Resource\ColorResource::COMMERCIALROUTEINCOMEBONUS
        - !php/const App\Modules\Demeter\Resource\ColorResource::COMMERCIALROUTEPRICEBONUS
      mandateDuration: 604800


    - id: !php/const App\Modules\Demeter\Resource\ColorResource::ADRANITE
      regime: !php/const App\Modules\Demeter\Model\Color::REGIME_ROYALISTIC
      bonus:
        - !php/const App\Modules\Demeter\Resource\ColorResource::TAXBONUS
        - !php/const App\Modules\Demeter\Resource\ColorResource::COLOPRICEBONUS
        - !php/const App\Modules\Demeter\Resource\ColorResource::LOOTRESOURCESMALUS
      mandateDuration: 1209600

    - id: !php/const App\Modules\Demeter\Resource\ColorResource::MALGAR
      regime: !php/const App\Modules\Demeter\Model\Color::REGIME_DEMOCRATIC
      bonus:
        - !php/const App\Modules\Demeter\Resource\ColorResource::DEFENSELITTLESHIPBONUS
        - !php/const App\Modules\Demeter\Resource\ColorResource::COMMANDERSCHOOLBONUS
        - !php/const App\Modules\Demeter\Resource\ColorResource::LITTLEACADEMICBONUS
      mandateDuration: 1382400
