imports:
    - { resource: ../src/Modules/Ares/Resource/config/config.yml }
    - { resource: ../src/Modules/Artemis/Resource/config/config.yml }
    - { resource: ../src/Modules/Athena/Resource/config/config.yml }
    - { resource: ../src/Modules/Atlas/Resource/config/config.yml }
    - { resource: ../src/Modules/Demeter/Resource/config/config.yml }
    - { resource: ../src/Modules/Gaia/Resource/config/config.yml }
    - { resource: ../src/Modules/Hephaistos/Resource/config/config.yml }
    - { resource: ../src/Modules/Hermes/Resource/config/config.yml }
    - { resource: ../src/Modules/Promethee/Resource/config/config.yml }
    - { resource: ../src/Modules/Zeus/Resource/config/config.yml }
parameters:
    # définition des ROOT
    app_root: '%env(APP_ROOT)%'
    getout_root: '%env(GETOUT_ROOT)%'
    system_path:		'%kernel.project_dir%/src'
    classes_path:       '%system_path%/Classes'

    modules: 		'%system_path%/Modules/'
    lib: 			'%classes_path%/lib/'
    config: 		'%system_path%/config/'
    event: 		'%system_path%/event/'

    inscription: 	'%system_path%/inscription/'
    connection: 	'%system_path%/connection/'

    action: 		'%system_path%/action/std/'
    ajax: 			'%system_path%/action/ajax/'

    api: 			'%system_path%/api/'
    script:		'%system_path%/script/'
    buffer:		'%system_path%/buffer/'

    template: 		'%system_path%/views/templates/'
    pages: 		'%system_path%/views/pages/'
    component: 	'%system_path%/views/components/'
    session_lifetime: 1800
    log_directory: var/logs
    log_rotation: 3
    daily_script_hour: 3
    gaia.galaxy_configuration.class: App\Modules\Gaia\Galaxy\GalaxyConfigurationV6
    game.available_factions: [1, 2, 3, 4, 7]

    apimode: '%env(APIMODE)%'

    server_id: '%env(SERVER_ID)%'
    server_cycle_timeout: '%env(SERVER_CYCLE_TIMEOUT)%'
    server_start_time: '%env(SERVER_START_TIME)%'

    security_api_key: '%env(SECURITY_API_KEY)%'
    security_server_key: '%env(SECURITY_SERVER_KEY)%'
    security_iv: '%env(SECURITY_IV)%'

    redis_timeout: '%env(REDIS_TIMEOUT)%'

    facebook_link: 'https://www.facebook.com/asylamba'
    google_plus_link: 'https://plus.google.com/+Asylamba-game'
    twitter_link: 'https://twitter.com/asylamba'

    # asm constantes
    asm_umode: true

    # event constantes
    event_base: 0 # correspond à une construction (batiment ou vaisseau) dans une base
    event_outgoing_attack: 1
    event_incoming_attack: 2

    # constante de temps pour la mise à jour des événements dans loadEvent.php
    # 300 s = 5 minutes
    time_event_update: 300

    # constantes pour le contre-espionnage
    antispy_out_of_circle:	0
    antispy_big_circle:	1
    antispy_middle_circle: 2
    antispy_little_circle: 3

    # pour Game::antiSpyRadius()
    antispy_display_mode: 0
    antispy_game_mode: 1

    nb_avatar: 80
    pam_coeftax: 1
    rsm_researchquantity: 10

    # durée en heures avant que le classement total démarre
    # 2 semaines = 336 h
    # 20 jours = 480h
    hours_before_start_of_ranking: 480
    points_to_win: 2000


    publicr: '/public/'
    css: '%publicr%css/'
    js: '%publicr%js/'
    media: '/media/'
    log: '%publicr%log/'
    # active les APIs de confirmation
    # active la création de personnage au niveau 5
    highmode: true
    # active les feuilles de style multiples par faction
    # note : les style peuvent ne pas être à jour
    color_style: true
    # active l'ajout du script analytics
    analytics: false
    # active la captation des données d'analyse (TB)
    data_analysis: false
    #########
    # INFOS #
    #########
    # défini le nom du tableau de session
    # note : utile si plusieurs instances cohabitent sur la même machine
    server_sess: 'server'
    # défini le titre du serveur (affiché comme titre)
    app_name: 'Asylamba'
    # défini le sous-titre du serveur (affiché comme titre)
    app_subname: 'Expansion Stellaire'
    # numéro de version de l'app
    app_version: '2.0.0'
    # créateurs du projet
    app_creator: 'Gil Clavien, Jacky Casas, Noé Zufferey'
    # défini la description du serveur (affichée dans la page)
    app_description: 'Asylamba, jeu par navigateur'
    #################
    # MISCELLANEOUS #
    #################
    # définition des ids des différants joueurs systèmes
    id_gaia: 1
    id_jeanmi: 2
    shift_faction: 2
    # date de début du serveur
    messenger_logs: '%env(default::MESSENGER_LOGS)%'
    sentry_dsn: '%env(default::SENTRY_DSN)%'
    database_host: '%env(DATABASE_HOST)%'
    database_name: '%env(DATABASE_NAME)%'
    database_user: '%env(DATABASE_USER)%'
    database_password: '%env(DATABASE_PASSWORD)%'
    database_admin_user: '%env(DATABASE_ADMIN_USER)%'
    database_admin_password: '%env(DATABASE_PASSWORD)%'

    env(MESSENGER_TRANSPORT_DSN): '%env(RABBITMQ_DSN)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/Kernel.php'
            - '../src/action/'
            - '../src/api/'
            - '../src/buffer/'
            - '../src/connection/'
            - '../src/event/'
            - '../src/inscription/'
            - '../src/script/'
            - '../src/views/'
            - '../src/Modules/'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    App\Shared\Infrastructure\Controller\:
        resource: '../src/Shared/Infrastructure/Controller/'
        tags: ['controller.service_arguments']

    App\Classes\Database\Database:
        public: true
        arguments:
            $host: "%database_host%"
            $name: "%database_name%"
            $user: "%database_user%"
            $password: "%database_password%"

    App\Classes\Database\DatabaseAdmin:
        arguments:
            $host: "%database_host%"
            $name: "%database_name%"
            $user: "%database_admin_user%"
            $password: "%database_admin_password%"

    Symfony\Component\Messenger\Bridge\Amqp\Transport\Connection:
        factory: ['Symfony\Component\Messenger\Bridge\Amqp\Transport\Connection', 'fromDsn']
        arguments: ['%env(RABBITMQ_DSN)%']

    Symfony\Component\Messenger\Bridge\Amqp\Transport\AmqpReceiver: ~

    App\Classes\Messenger\SendersLocator:
        factory: ['App\Classes\Messenger\SendersLocator', 'instanciate']

    messenger.default_bus:
        class: Symfony\Component\Messenger\MessageBus
        factory: ['App\Classes\Messenger\BusFactory', 'createBus']
        arguments:
            $handlersLocator: '@messenger.default_bus.messenger.handlers_locator'
            $enableLogs: '%messenger_logs%'
        tags:
            - { name: 'messenger.bus' }

    Symfony\Component\Messenger\MessageBusInterface:
        alias: 'messenger.default_bus'

    Symfony\Component\Messenger\Worker:
        public: true
        arguments:
            $receivers: ['@Symfony\Component\Messenger\Bridge\Amqp\Transport\AmqpReceiver']

    App\Classes\Library\Session\SessionWrapper: ~

    App\Classes\Scheduler\CyclicActionScheduler:
        public: true
        arguments:
            $dailyScriptHour: "%daily_script_hour%"

    App\Classes\Router\Router:
        arguments:
            $appRoot: '%app_root%'
            $rootPath: '%kernel.project_dir%'
            $getOutRoot: "%getout_root%"
            $actionPath: '%action%'
            $ajaxPath: '%ajax%'
            $connectionPath: '%connection%'
            $registrationPath: '%inscription%'
            $bufferPath: '%buffer%'
            $apiPath: '%api%'
            $templatePath: '%template%'
            $scriptPath: '%script%'
            $pagesPath: '%pages%'
            $eventPath: '%event%'

    App\Classes\Library\Http\RequestFactory: ~

    App\Classes\Library\Http\ResponseFactory:

    App\Classes\Daemon\ClientManager:
        arguments:
            $sessionLifetime: "%session_lifetime%"

    App\Classes\Templating\Renderer: ~

    App\Classes\Entity\EntityManager:
        public: true

    App\Classes\Logger\ConsoleLogger: ~

    App\Classes\Logger\FileLogger:
        arguments:
            $logDirectory: "%log_directory%"
            $logRotation: "%log_rotation%"

    Psr\Log\LoggerInterface: '@App\Classes\Logger\ConsoleLogger'

    App\Classes\Library\Parser:
        arguments:
            $appRoot: '%app_root%'
            $mediaPath: '%media%'

    App\Classes\Worker\API:
        arguments:
            $serverId: "%server_id%"
            $apiKey: "%security_api_key%"
            $getOutRoot: "%getout_root%"

    App\Classes\Library\Security:
        arguments:
            $serverKey: "%security_server_key%"
            $iv: "%security_iv%"

    App\Classes\Memory\MemoryManager: ~

    App\Classes\Redis\RedisManager:
        arguments:
            $host: '%env(REDIS_HOST)%'
            $port: '%env(int:REDIS_PORT)%'
            $password: '%env(default::REDIS_PASSWORD)%'
            $timeout: "%redis_timeout%"

    App\Classes\EventSubscriber\ExceptionSubscriber:
        arguments:
            $templatePath: '%template%'
        tags: ['kernel.event_subscriber']

    App\Shared\Infrastructure\EventListener\MixpanelListener:
        arguments:
            $environment: '%kernel.environment%'
