services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Shared\Infrastructure\Log\DatadogLogProcessor:
        tags:
            - { name: monolog.processor, handler: nested }
