---
services:
    _defaults:
        autowire: true
        autoconfigure: true

    _instanceof:
        App\Shared\Application\SchedulerInterface:
            tags: ['app.scheduler']

    App\Modules\Demeter\:
        resource: '%kernel.project_dir%/src/Modules/Demeter/'
        exclude:
            - '../../Message'
            - '../../Model'
            - '../../Repository'
            - '../../Resource'
