---
services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    _instanceof:
        Symfony\Component\Messenger\Handler\MessageHandlerInterface:
            tags:
                - { name: 'messenger.message_handler', bus: 'messenger.default_bus' }

    App\Modules\Demeter\Handler\:
        resource: '%kernel.project_dir%/src/Modules/Demeter/Handler/*'

    App\Modules\Demeter\Manager\:
        resource: '%kernel.project_dir%/src/Modules/Demeter/Manager/*'
