---
services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Modules\Demeter\:
        resource: '%kernel.project_dir%/src/Modules/Demeter/'
        exclude:
            - '../../Message'
            - '../../Model'
            - '../../Repository'
            - '../../Resource'
