---
services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    _instanceof:
        Symfony\Component\Messenger\Handler\MessageHandlerInterface:
            tags:
                - { name: 'messenger.message_handler', bus: 'messenger.default_bus' }

    Asylamba\Modules\Demeter\Manager\:
        resource: '%root_path%/system/Modules/Demeter/Manager/*'
