---
parameters:
    gaia.limit_conquest_sector: 4
    gaia.scores: [1, 3, 5, 10]
    gaia.sector_minimal_score: 10
    
services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Modules\Gaia\:
        resource: '%kernel.project_dir%/src/Modules/Gaia/'
        exclude:
            - '../../Message'
            - '../../Model'
            - '../../Repository'
            - '../../Resource'

    App\Modules\Gaia\Helper\ActionHelper:
        arguments:
            $rootPath: '%kernel.project_dir%'
            $mediaPath: '%media%'
            $routeSectorBonus: "%athena.trade.route.sector_bonus%"
            $routeColorBonus: "%athena.trade.route.color_bonus%"

    App\Modules\Gaia\Helper\GalaxyGenerator: ~
            
    App\Modules\Gaia\Manager\GalaxyColorManager:
        arguments:
            $availableFactions: "%game.available_factions%"
            $limitConquestSector: "%gaia.limit_conquest_sector%"

    App\Modules\Gaia\Manager\PlaceManager:
        arguments:
            $mediaPath: "%media%"

    App\Modules\Gaia\Manager\SectorManager:
        arguments:
            $scores: "%gaia.scores%"
            
    App\Modules\Gaia\Galaxy\GalaxyConfiguration:
        public: true
        class: "%gaia.galaxy_configuration.class%"
        
    App\Modules\Gaia\EventListener\SectorListener:
        arguments:
            $scores: "%gaia.scores%"
            $sectorMinimalScore: "%gaia.sector_minimal_score%"
        tags:
            - {name: "kernel.event_listener", event: "gaia.place_owner_change", method: "onPlaceOwnerChange", priority: 1}
            
    App\Modules\Gaia\EventListener\SystemListener:
        arguments:
            $scores: "%gaia.scores%"
        tags:
            - {name: "kernel.event_listener", event: "gaia.place_owner_change", method: "onPlaceOwnerChange", priority: 2}
