---
services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    _instanceof:
        Symfony\Component\Messenger\Handler\MessageHandlerInterface:
            tags:
                - { name: 'messenger.message_handler', bus: 'messenger.default_bus' }

    #App\Modules\Artemis\Handler\:
    #    resource: '%kernel.project_dir%/src/Modules/Artemis/Handler/*'

    App\Modules\Artemis\Manager\:
        resource: '%kernel.project_dir%/src/Modules/Artemis/Manager/*'
